### ISSUE TITLE
Basic commands such as ros2 node list sometimes fails in ROS2 humble

### ISSUE THREAD

**Issue by kminoda** [ros2/ros2#1292]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries 
- Version or commit hash:
  - humble 
- DDS implementation:
  - CycloneDDS 
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
The basic command of ROS2 such as follows failed with an unfamiliar error message.
```
ros2 node list
```
```
ros2 topic list
```
Here's the error message:
```
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.3', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/command/node.py", line 37, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/verb/list.py", line 38, in main
    node_names = get_node_names(node=node, include_hidden_nodes=args.all)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/api/__init__.py", line 60, in get_node_names
    node_names_and_namespaces = node.get_node_names_and_namespaces()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'rclpy._rclpy_pybind11.RCLError'>:Failed to get node names: rcl node's context is invalid, at ./src/rcl/node.c:428">
```
Rebooting the PC solved this issue.
I encountered this issue twice, both of which I couldn't tell the reason why. Thus, I still cannot reproduce the issue in a certain way.

#### Additional information

----

**Comment by fujitatomoya** [comment]
@kminoda thanks for posting the issue.

there are a few comments and questions,

- i cannot reproduce the issue neither with `rmw_fastrtps_cpp` nor `rmw_cyclonedds_cpp`. (`while true; do ros2 node list; ros2 topic list; done`)
- does this problem happen with `export RMW_IMPLEMENTATION=rmw_fastrtps_cpp` which is default?
- possible work-around could be the following, to restart the ros2 daemon(xmlrpc server).

```bash
# when problem happens, issue the following command to see if the problem can be resolved.
ros2 daemon stop
ros2 daemon start
ros2 topic list
ros2 node list
```

**Comment by kminoda** [comment]
@fujitatomoya Thank you!
I am sorry (and also glad) that it was only twice that I met this issue (both of which occurred with `RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`), and I cannot reproduce it any longer. 

As additional info, I figured out that one of my colleagues also encountered a similar error with `ros2 node list` with a similar setup (Ubuntu 22.04, ROS2 humble, CycloneDDS). It also disappeared by rebooting the system as well.
```
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.3', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/command/node.py", line 37, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/verb/list.py", line 38, in main
    node_names = get_node_names(node=node, include_hidden_nodes=args.all)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2node/api/__init__.py", line 60, in get_node_names
    node_names_and_namespaces = node.get_node_names_and_namespaces()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'rclpy._rclpy_pybind11.InvalidHandle'>:cannot use Destroyable because destruction was requested">
```

**Comment by kminoda** [comment]
I figured out the cause. It was my fault.

The ros2 nodes sometimes linger even though I killed the process with ctrl-c, so to address this issue, I have my own script to clean up the processes related to ros2. It turned out that the script killed the following process, which seemed to cause the above issue:
```minoda    650959  0.6  0.1 691732 48772 pts/3    Sl   17:02   0:01 /usr/bin/python3 -c from ros2cli.daemon.daemonize import main; main() --name ros2-daemon --ros-domain-id 0 --rmw-implementation rmw_cyclonedds_cpp```
