### ISSUE TITLE
Underscores in the package name is changed to hyphen, when using --symlink-install 

### ISSUE THREAD

**Issue by farzadsw** [ros2/ros2#1315]
## Bug report

- Operating System:
  Ubuntu 22.04 (VM on a M2 macbook)
- Installation type:
  binaries
- Version or commit hash:
 humble

#### Steps to reproduce issue
I use ROS2 Humble on Ubuntu 22.04, with setuptools version 58.2.0.
When I build a package with the "--symlink-install" flag, the built node has different name ( "_" changed to "-") and gives me error:

```
colcon build --packages-select my_py_pkg --symlink-install 

Starting >>> my_py_pkg
Finished <<< my_py_pkg [0.47s]          

Summary: 1 package finished [0.55s]
```

#### Expected behavior
Be able to run the py_node inside my_py_pkg

#### Actual behavior
```
ros2 run my_py_pkg py_node 
Traceback (most recent call last):
  File "/home/farzad/ros2_ws/install/my_py_pkg/lib/my_py_pkg/py_node", line 33, in <module>
    sys.exit(load_entry_point('my-py-pkg', 'console_scripts', 'py_node')())
  File "/home/farzad/ros2_ws/install/my_py_pkg/lib/my_py_pkg/py_node", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for my-py-pkg
[ros2run]: Process exited with failure 1
```

#### Additional information

This is the py_node (the built node) file:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'my-py-pkg','console_scripts','py_node'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'my-py-pkg'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('my-py-pkg', 'console_scripts', 'py_node')())
```

and this is my setup.py file in the package:

```
from setuptools import setup

package_name = 'my_py_pkg'

setup(
    name=package_name,
    version='0.0.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='farzad',
    maintainer_email='farzadsw@gmail.com',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            "py_node = my_py_pkg.my_first_node:main"
        ],
    },
)
```

**Comment by farzadsw** [comment]
The sourcing setup.bash solved the running error
