### ISSUE TITLE
No module named 'numpy.core._multiarray_umath' when installing carla-ros-bridge

### ISSUE THREAD

**Issue by mgmike** [ros2/ros2#1338]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04 (upgraded from 18.04)
- Installation type: [from binary](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html)
- Version or commit hash: Ros2 Foxy
- DDS implementation: default for Foxy
- Client library (if applicable): carla-ros-bridge (0.9.13)

#### Steps to reproduce issue

Installed Unreal Engine and [Carla 0.9.13 from source](https://carla.readthedocs.io/en/latest/build_linux/) with python3.8 and clang 10
Installing [carla ros bridge 0.9.13 from source](https://carla.readthedocs.io/projects/ros-bridge/en/latest/ros_installation_ros2/)

#### Expected behavior
Should build on 
`colcon build`

#### Actual behavior
I get python errors:

```Starting >>> carla_msgs
Starting >>> ros_compatibility
Starting >>> carla_common
Starting >>> carla_ros_scenario_runner_types
--- stderr: carla_msgs                                                                                                                                              
ImportError in template '/home/mike/ros2_foxy/install/rosidl_generator_py/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

ImportError when expanding '_idl.py.em' into '/home/mike/carla-ros-bridge/build/carla_msgs/rosidl_generator_py/carla_msgs/msg/_carla_bounding_box.py': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

Error processing idl file: /home/mike/carla-ros-bridge/build/carla_msgs/rosidl_adapter/carla_msgs/msg/CarlaBoundingBox.idl
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/ros2_foxy/install/rosidl_generator_py/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
    sys.exit(main())
  File "/home/mike/ros2_foxy/install/rosidl_generator_py/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
    return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
    generate_files(generator_arguments_file, mapping)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
    raise(e)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 91, in generate_files
    post_process_callback=post_process_callback)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
    interpreter.string(template_content, template_path, locals=data)
  File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1547, in run
    self.subrun(info[0][1], interpreter, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1631, in subrun
    token.run(interpreter, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 5, in <module>
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
    interpreter.string(content, str(template_path), kwargs)
  File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 3, in <module>
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

Exception ignored in: <bound method Interpreter.__del__ of <empy pseudomodule/interpreter at 0x7f4aa8b2a2e8>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/em.py", line 2094, in __del__
  File "/usr/lib/python3/dist-packages/em.py", line 2157, in shutdown
  File "/usr/lib/python3/dist-packages/em.py", line 2646, in finalize
  File "/usr/lib/python3/dist-packages/em.py", line 2200, in push
AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
make[2]: *** [carla_msgs__py/CMakeFiles/carla_msgs__py.dir/build.make:206: rosidl_generator_py/carla_msgs/_carla_msgs_s.ep.rosidl_typesupport_introspection_c.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:553: carla_msgs__py/CMakeFiles/carla_msgs__py.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< carla_msgs [0.89s, exited with code 2]
Aborted  <<< carla_ros_scenario_runner_types [0.90s]                                                                                             
Aborted  <<< ros_compatibility [0.93s]
Aborted  <<< carla_common [0.92s]

Summary: 0 packages finished [1.22s]
  1 package failed: carla_msgs
  3 packages aborted: carla_common carla_ros_scenario_runner_types ros_compatibility
  2 packages had stderr output: carla_msgs carla_ros_scenario_runner_types
  15 packages not processed
```

#### Additional information
I make sure to `source /opt/ros/foxy/setup.bash`
I have also installed ros2 foxy from source successfully and have tried sourcing ~/ros2_foxy/install/local_setup.bash which resulted in a similar error
I make sure python3.8 is used. Since I did update from Ubuntu18, python2.7 is still installed. 
Python3.8 is chosen for update-alternatives for both python and python3.
Part of the error tells me that numpy cannot be found, but i get the same error when installing numpy from either apt or pip and pip3 or both for python3.8. I do have anaconda installed, but I am not using it and it is not sourced in my .bashrc. 

My $PYTHONPATH is: /opt/ros/foxy/bin:/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-17-oracle/bin:/usr/lib/jvm/java-17-oracle/db/bin

My $PATH is: /opt/ros/foxy/lib/python3.8/site-packages

The error also mentions that I should be using python3.6 and that numpy isnt installed for python3.6. So I have also tried to changed update-alternatives to point at python3.6 for both python and python3, and added /usr/bin/python3.6 to the beginning of both PATH and PYTHONPATH but I still get the same error. 

I appreciate any help, I'm sure you can see I have been going crazy attempting different configurations these past few days.

**Comment by clalancette** [comment]
It's clear that you still have something configured with Python 3.6 somewhere.  My suggestion is that you uninstall anything related to Python 3.6, as well as all of your pip packages, and then reinstall.

Another option is to use a 20.04 container for this.

Finally, it may just be easier to reinstall Ubuntu 20.04 from scratch, and that will give you a clean environment.

With all of that said, this is in all likelihood a problem in your environment, so I'm going to close this.  If you are still having problems and need help, please ask questions like this at https://answers.ros.org, our central Questions-and-Answers site.
