### ISSUE TITLE
importlib.metadata.PackageNotFoundError: ros2cli

### ISSUE THREAD

**Issue by Cherub1Zhuang** [ros2/ros2#1416]
## Bug report
**Required Info:**
- Operating System:
  - Windows 10
- Installation type:
  - source
- Version or commit hash:
  -  release version
#### Steps to reproduce issue

```
In the Windows environment, when installing ROS2, the previous installation follows the doc and is executed at the end
ros2 run demo_ nodes_ cpp talker
The following error occurred during:

Traceback (most recent call last):
  File "C:\dev\ros2_humble\Scripts\ros2-script.py", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.9.13', 'console_scripts', 'ros2')())
  File "C:\dev\ros2_humble\Scripts\ros2-script.py", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "C:\Python38\lib\importlib\metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Python38\lib\importlib\metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ros2cli

```

**Comment by clalancette** [comment]
Can you please give us more detailed information on exactly the steps you took?  As far as we know this works OK elsewhere, so there may be something in your environment that is subtly different.

**Comment by clalancette** [comment]
No response in 3 weeks here, so I'm going to close this out.

**Comment by Toskies** [comment]
do you resolve this question?   I have the same question.

**Comment by mengxyokok** [comment]
the same qustion

**Comment by yihangy** [comment]
the same qustion

**Comment by wittrup** [comment]
This should be reopened.  Have the same question.
Followed Installation guide [Windows (binary)](https://docs.ros.org/en/jazzy/Installation/Windows-Install-Binary.html#windows-binary)
```
C:\Users\wittr>ros2 run demo_nodes_cpp talker
Traceback (most recent call last):
  File "C:\dev\ros2_jazzy\Scripts\ros2-script.py", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.32.2', 'console_scripts', 'ros2')())
  File "C:\dev\ros2_jazzy\Scripts\ros2-script.py", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "C:\Python38\lib\importlib\metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Python38\lib\importlib\metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ros2cli
```

**Comment by ArthurFleischman** [comment]
same error on windows10
