### ISSUE TITLE
rosbag failure

### ISSUE THREAD

**Issue by alonsnir** [ros2/ros2#1422]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04, kernel 5.15.0-71-generic
- Installation type:
  - binaries
- Version or commit hash:
  - Humble
- DDS implementation:
  - 
- Client library (if applicable):
  - rosbag

#### Steps to reproduce issue

```
rosbag record -a
Traceback (most recent call last):
  File "/usr/bin/rosbag", line 34, in <module>
    import rosbag
  File "/usr/lib/python3/dist-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/usr/lib/python3/dist-packages/rosbag/bag.py", line 69, in <module>
    import rospy
  File "/usr/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/usr/lib/python3/dist-packages/rospy/client.py", line 54, in <module>
    import rospy.core
  File "/usr/lib/python3/dist-packages/rospy/core.py", line 75, in <module>
    from rosgraph_msgs.msg import Log
ImportError: cannot import name 'Log' from 'rosgraph_msgs.msg' (/opt/ros/humble/local/lib/python3.10/dist-packages/rosgraph_msgs/msg/__init__.py)
```

#### Additional information

```
ros2 pkg list | grep -v installed | grep rosgraph_msgs
rosgraph_msgs
```

**Comment by clalancette** [comment]
> rosbag record -a

This is a ROS 1 command.  You should use `ros2 bag record -a`.
