### ISSUE TITLE
[ROS2 humble] unable to successfully use python virtualenv

### ISSUE THREAD

**Issue by CoderWangcai** [ros2/ros2#1469]
## Bug report
I am trying to use a python virtualenv environment (**python3.8**) under ROS2 humble. I'm following the instructions given in this [tutorial](https://index.ros.org/doc/ros2/Tutorials/Using-Python-Packages/#installing-via-a-virtual-environment) and [issues-1094](https://github.com/ros2/ros2/issues/1094). But I encountered the problem with `No module named 'rclpy._rclpy_pybind11`.

**Required Info:**

- Operating System: Ubuntu 22.04.2 LTS
- Installation type: binaries
- Version or commit hash: Humble Hawksbill
- DDS implementation: the default DDS vendor is eProsima’s Fast DDS
- Client library (if applicable): N/A

#### Steps to reproduce issue
- mkdir ros2 workspace
```
mkdir -p /home/users/siyu.zhou/CODE/colcon_venv/src
cd /home/users/siyu.zhou/CODE/colcon_venv
```
- install virtualenv from /usr/local/python3.8
```
/usr/local/python3.8/bin/python3.8 -m pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple
```
- create venv and source
```
/usr/local/python3.8/bin/python3.8 -m virtualenv venv --system-site-packages --symlinks
source venv/bin/activate
```
- create ros2 packages
```
cd src
ros2 pkg create venv --build-type ament_python
```
- touch a new python file in `src/venv/ven/venv.py`
```
import rclpy
from rclpy.node import Node
import sys

class ExampleNode(Node):
    def __init__(self):
        super().__init__('sensors')
        self.get_logger().info("ExampleNode started")
        self.get_logger().info(f"python path: {sys.executable}")

def main(args=None):
    rclpy.init(args=args)
    node = ExampleNode()
    rclpy.spin(node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
```
- revised the `src/setup.py`
```
from setuptools import setup

package_name = 'venv'

setup(
    name=package_name,
    version='0.0.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='root',
    maintainer_email='root@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            "venv = venv.venv:main"
        ],
    },
)
```
- revised the `src/setup.cfg`
```
[build_scripts]
executable = /usr/bin/env python3
[develop]
script_dir=$base/lib/venv
[install]
install_scripts=$base/lib/venv
```
- colcon build
```
cd /home/users/siyu.zhou/CODE/colcon_venv
python3 -m pip install -U colcon-common-extensions -i https://pypi.tuna.tsinghua.edu.cn/simple
python3 -m colcon build --symlink-install --packages-select venv
```
- run the node
```
source install/setup.bash
ros2 pkg executables venv
ros2 run venv venv
```

#### Expected behavior
The returned python path should show ${workspaceFolder}/venv/bin/python and any packages installed in the virtual environment should be accessible inside the node.

#### Actual behavior
```
(venv) root@bc535c5e32fe:/home/users/siyu.zhou/CODE/colcon_venv# ros2 run venv venv 
sys.path=
['/home/users/siyu.zhou/CODE/colcon_venv/install/venv/lib/venv', '/home/users/siyu.zhou/CODE/colcon_venv/build/venv', '/home/users/siyu.zhou/CODE/colcon_venv/install/venv/lib/python3.8/site-packages', '/opt/ros/humble/lib/python3.10/site-packages', '/opt/ros/humble/local/lib/python3.10/dist-packages', '/usr/local/python3.8/lib/python38.zip', '/usr/local/python3.8/lib/python3.8', '/usr/local/python3.8/lib/python3.8/lib-dynload', '/home/users/siyu.zhou/CODE/colcon_venv/venv/lib/python3.8/site-packages', '/usr/local/python3.8/lib/python3.8/site-packages']
Traceback (most recent call last):
  File "/home/users/siyu.zhou/CODE/colcon_venv/install/venv/lib/venv/venv", line 33, in <module>
    sys.exit(load_entry_point('venv', 'console_scripts', 'venv')())
  File "/home/users/siyu.zhou/CODE/colcon_venv/install/venv/lib/venv/venv", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/python3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/python3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/users/siyu.zhou/CODE/colcon_venv/build/venv/venv/venv.py", line 6, in <module>
    import rclpy
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 49, in <module>
    from rclpy.signals import install_signal_handlers
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/signals.py", line 15, in <module>
    from rclpy.exceptions import InvalidHandle
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/exceptions.py", line 15, in <module>
    from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
    rclpy_implementation = import_c_library('._rclpy_pybind11', package)
  File "/opt/ros/humble/lib/python3.10/site-packages/rpyutils/import_c_library.py", line 39, in import_c_library
    return importlib.import_module(name, package=package)
  File "/usr/local/python3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
The C extension '/opt/ros/humble/lib/python3.10/site-packages/_rclpy_pybind11.cpython-38-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://docs.ros.org/en/humble/Guides/Installation-Troubleshooting.html#import-failing-without-library-present-on-the-system' for possible solutions
[ros2run]: Process exited with failure 1
```

**Comment by sara9915** [comment]
Hi, I have the same error. Did you find a solution to the problem?
I think it is necessary to build ROS2 from source with python3.8 but I'm not sure this is the optimal solution..
