### ISSUE TITLE
Error in building ROS2 workspace

### ISSUE THREAD

**Issue by gaurav713914** [ros2/ros2#1470]
While running the` colcon build --symlink-install` command we are getting the following error:

```
Starting >>> crazyflie_interfaces
Starting >>> motion_capture_tracking_interfaces
--- stderr: crazyflie_interfaces                                         
CMake Error at /opt/ros/galactic/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/home/mocaplab/anaconda3/bin/python3 -m rosidl_adapter
  --package-name crazyflie_interfaces --arguments-file
  /home/mocaplab/ros2_ws/build/crazyflie_interfaces/rosidl_adapter__arguments__crazyflie_interfaces.json
  --output-dir
  /home/mocaplab/ros2_ws/build/crazyflie_interfaces/rosidl_adapter/crazyflie_interfaces
  --output-file
  /home/mocaplab/ros2_ws/build/crazyflie_interfaces/rosidl_adapter/crazyflie_interfaces.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/home/mocaplab/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/home/mocaplab/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/main.py", line 55, in main
      pathlib.Path(relative_path), output_dir)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 18, in convert_to_idl
      from rosidl_adapter.msg import convert_msg_to_idl
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 16, in <module>
      from rosidl_adapter.resource import expand_template
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
      import em

  ModuleNotFoundError: No module named 'em'

Call Stack (most recent call first):
  /opt/ros/galactic/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:20 (rosidl_generate_interfaces)


---
Failed   <<< crazyflie_interfaces [0.27s, exited with code 1]
Aborted  <<< motion_capture_tracking_interfaces [0.26s]

Summary: 0 packages finished [0.42s]
  1 package failed: crazyflie_interfaces
  1 package aborted: motion_capture_tracking_interfaces
  2 packages had stderr output: crazyflie_interfaces motion_capture_tracking_interfaces
  5 packages not processed
```

**Comment by clalancette** [comment]
> ModuleNotFoundError: No module named 'em'

It looks like you are missing the `python3-empy` dependency.

Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
