### ISSUE TITLE
ros2 param load /turtlesim turtlesim.yaml error

### ISSUE THREAD

**Issue by Waltub** [ros2/ros2#1528]
## Bug report
Hello, I'm new and I'm going through the tutorials when this issue happened.  Can someone tell me what I'm doing wrong?
**Required Info:**

- Operating System:
  - Windows 11

#### Steps to reproduce issue

```
ros2 param load /turtlesim turtlesim.yaml
```

#### Expected behavior
Set parameter background_b successful
Set parameter background_g successful
Set parameter background_r successful
Set parameter qos_overrides./parameter_events.publisher.depth failed: parameter 'qos_overrides./parameter_events.publisher.depth' cannot be set because it is read-only
Set parameter qos_overrides./parameter_events.publisher.durability failed: parameter 'qos_overrides./parameter_events.publisher.durability' cannot be set because it is read-only
Set parameter qos_overrides./parameter_events.publisher.history failed: parameter 'qos_overrides./parameter_events.publisher.history' cannot be set because it is read-only
Set parameter qos_overrides./parameter_events.publisher.reliability failed: parameter 'qos_overrides./parameter_events.publisher.reliability' cannot be set because it is read-only
Set parameter use_sim_time successful
#### Actual behavior
Traceback (most recent call last):
  File "C:\dev\ros2_iron\Scripts\ros2-script.py", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.25.5', 'console_scripts', 'ros2')())
  File "C:\dev\ros2_iron\Lib\site-packages\ros2cli\cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "C:\dev\ros2_iron\Lib\site-packages\ros2param\command\param.py", line 39, in main
    return extension.main(args=args)
  File "C:\dev\ros2_iron\Lib\site-packages\ros2param\verb\load.py", line 53, in main
    load_parameter_file(node=node, node_name=node_name, parameter_file=args.parameter_file,
  File "C:\dev\ros2_iron\Lib\site-packages\ros2param\api\__init__.py", line 49, in load_parameter_file
    future = client.load_parameter_file(parameter_file, use_wildcard)
  File "C:\dev\ros2_iron\Lib\site-packages\rclpy\parameter_client.py", line 312, in load_parameter_file
    param_dict = parameter_dict_from_yaml_file(parameter_file, use_wildcard)
  File "C:\dev\ros2_iron\Lib\site-packages\rclpy\parameter.py", line 286, in parameter_dict_from_yaml_file
    param_file = yaml.safe_load(f)
  File "C:\Python38\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Python38\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Python38\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Python38\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Python38\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Python38\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Python38\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "turtlesim.yaml", position 3
#### Additional information

----

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
