### ISSUE TITLE
ROS2 Humble create package error

### ISSUE THREAD

**Issue by luciaabyss** [ros2/ros2#1532]
## Bug report

**Required Info:**

- Operating System:
  - ubuntu22.04
- Installation type:
  - source
- Version or commit hash:
  - current humble
- DDS implementation:
  - default

#### Steps to reproduce issue
When i  trying to create a new package use this command in vscode: 
ros2 pkg create --build-type ament_cmake --license Apache-2.0 --node-name my_node my_package

it doesn't work with msg:

Traceback (most recent call last):
  File "/home/alpha/ros2_humble/install/ros2cli/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli', 'console_scripts', 'ros2')())
  File "/home/alpha/ros2_humble/install/ros2cli/bin/ros2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alpha/ros2_humble/build/ros2cli/ros2cli/cli.py", line 22, in <module>
    from rclpy.executors import ExternalShutdownException
  File "/home/alpha/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 49, in <module>
    from rclpy.signals import install_signal_handlers
  File "/home/alpha/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/signals.py", line 15, in <module>
    from rclpy.exceptions import InvalidHandle
  File "/home/alpha/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/exceptions.py", line 15, in <module>
    from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
  File "/home/alpha/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
    rclpy_implementation = import_c_library('._rclpy_pybind11', package)
  File "/home/alpha/ros2_humble/build/rpyutils/rpyutils/import_c_library.py", line 39, in import_c_library
    return importlib.import_module(name, package=package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtracetools.so: cannot open shared object file: No such file or directory
The C extension '/home/alpha/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/_rclpy_pybind11.cpython-310-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://docs.ros.org/en/{distro}/Guides/Installation-Troubleshooting.html#import-failing-even-with-library-present-on-the-system' for possible solutions

Everything is ok before i install CUDA and cudnn, but i think there has no relationship with these two things. I wonder how this happened and how to solve this.

**Comment by cottsay** [comment]
It looks like your workspace at `/home/alpha/ros2_humble` needs to be rebuilt after changes to your system. I recommend removing the `build` and `install` subdirectories of that workspace and building again the beginning.

In the future, please seek technical help for issues like this in supported channels like the [Robotics Stack Exchange](https://robotics.stackexchange.com/) or [Open Robotics Discord](https://discord.com/servers/open-robotics-1077825543698927656). Tickets on GitHub are used for tracking software bugs and enhancements.
