### ISSUE TITLE
Log files seem to miss crucial logs compared to console output

### ISSUE THREAD

**Issue by wouterio** [ros2/ros2#1636]
## Bug report

Log files seem to miss crucial logs compared to console output. The console output contains a stacktrace:
```
oddbot@oddbot-fitlet:~/Documents/repos/vision-ros$ ros2 launch vision_launch carrier.launch.py
[INFO] [launch]: All log files can be found below /home/oddbot/OddBotVisionLocal/log/2024-12-10-10-39-59-270904-oddbot-fitlet-43424
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [carrier_camera_node-1]: process started with pid [43437]
[INFO] [speed_calculator_node-2]: process started with pid [43439]
[INFO] [front_ridge_detector_node-3]: process started with pid [43441]
[INFO] [field_node-4]: process started with pid [43443]
[INFO] [parameter_storage_node-5]: process started with pid [43445]
[INFO] [cpu_monitor.py-6]: process started with pid [43447]
[INFO] [ram_monitor.py-7]: process started with pid [43449]
[INFO] [sensors_monitor.py-8]: process started with pid [43451]
[sensors_monitor.py-8] [INFO] [1733823601.594960961] [carrier.sensors_monitor]: Ignore fanspeed warnings: False
[parameter_storage_node-5] [INFO] [1733823604.736519092] [carrier.parameter_storage_node]: Reading parameter file
[field_node-4] Traceback (most recent call last):
[field_node-4]   File "/home/oddbot/Documents/repos/vision-ros/install/field/lib/field/field_node", line 33, in <module>
[field_node-4]     sys.exit(load_entry_point('field', 'console_scripts', 'field_node')())
[field_node-4]   File "/home/oddbot/Documents/repos/vision-ros/build/field/field/field_node.py", line 56, in main
[field_node-4]     run_node(node, args)
[field_node-4]   File "/home/oddbot/Documents/repos/vision-ros/build/common/common/ros/utils.py", line 12, in run_node
[field_node-4]     executor.spin()
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 294, in spin
[field_node-4]     self.spin_once()
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
[field_node-4]     self._spin_once_impl(timeout_sec)
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
[field_node-4]     raise handler.exception()
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[field_node-4]     self._handler.send(None)
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
[field_node-4]     await call_coroutine(entity, arg)
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
[field_node-4]     await await_or_execute(sub.callback, msg)
[field_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[field_node-4]     return callback(*args)
[field_node-4]   File "/home/oddbot/Documents/repos/vision-ros/build/field/field/field_node.py", line 37, in __front_line_callback
[field_node-4]     raise Exception('Test')
[field_node-4] Exception: Test
[ERROR] [field_node-4]: process has died [pid 43443, exit code 1, cmd '/home/oddbot/Documents/repos/vision-ros/install/field/lib/field/field_node --ros-args -r __ns:=/carrier --params-file /home/oddbot/Documents/repos/vision-ros/install/vision_launch/share/vision_launch/config/carrier_default_configs.yaml --params-file /home/oddbot/OddBotVisionLocal/config/carrier_configs.yaml -r front_line:=lane_center_deviation -r crop_line:=aggregate/mean_line -r field_ahead:=field_ahead -r field_below:=field_below'].
```
The `launch.log` file:
```
1733823599.2720761 [INFO] [launch]: All log files can be found below /home/oddbot/OddBotVisionLocal/log/2024-12-10-10-39-59-270904-oddbot-fitlet-43424
1733823599.2723072 [INFO] [launch]: Default logging verbosity is set to INFO
1733823600.5963511 [INFO] [carrier_camera_node-1]: process started with pid [43437]
1733823600.5966482 [INFO] [speed_calculator_node-2]: process started with pid [43439]
1733823600.5967853 [INFO] [front_ridge_detector_node-3]: process started with pid [43441]
1733823600.6013193 [INFO] [field_node-4]: process started with pid [43443]
1733823600.6016035 [INFO] [parameter_storage_node-5]: process started with pid [43445]
1733823600.6017628 [INFO] [cpu_monitor.py-6]: process started with pid [43447]
1733823600.6019068 [INFO] [ram_monitor.py-7]: process started with pid [43449]
1733823600.6020689 [INFO] [sensors_monitor.py-8]: process started with pid [43451]
1733823610.5817583 [ERROR] [field_node-4]: process has died [pid 43443, exit code 1, cmd '/home/oddbot/Documents/repos/vision-ros/install/field/lib/field/field_node --ros-args -r __ns:=/carrier --params-file /home/oddbot/Documents/repos/vision-ros/install/vision_launch/share/vision_launch/config/carrier_default_configs.yaml --params-file /home/oddbot/OddBotVisionLocal/config/carrier_configs.yaml -r front_line:=lane_center_deviation -r crop_line:=aggregate/mean_line -r field_ahead:=field_ahead -r field_below:=field_below'].
```
But the `python3_43443_1733823602164.log` file associated with `field_node`'s pid `43443` is empty.

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - Binaries
- Version or commit hash:
  - Humble
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
- Run any node throwing an exception.
- The console shows the exception stacktrace.
- Find the log file associated to that node.
- The log file does not contain the exception stacktrace.

#### Expected behavior
The log file associated to a node throwing an exception should contain the exception stacktrace.

#### Actual behavior
The log file associated to a node throwing an exception does not contain the exception stacktrace.

**Comment by sloretz** [comment]
I'm not able to reproduce with ROS Rolling. What does your launch file look like? Are you able to reproduce with this package? [mre1636.zip](https://github.com/user-attachments/files/18214506/mre1636.zip)

```xml
<launch>
  <node pkg="mre1636" exec="raises_exception" name="raises_exception" />
</launch>
```

```python
import rclpy

def main():
    raise RuntimeError("Some exception!")


if __name__ == '__main__':
    main()
```

The console
```bash
$ ros2 launch mre1636 mre.launch.xml
[INFO] [launch]: All log files can be found below /home/ros/.ros/log/2024-12-20-19-11-59-571676-5200755c994a-255183
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [raises_exception-1]: process started with pid [255187]
[raises_exception-1] Traceback (most recent call last):
[raises_exception-1]   File "/workspaces/ros2/install/mre1636/lib/mre1636/raises_exception", line 33, in <module>
[raises_exception-1]     sys.exit(load_entry_point('mre1636==0.1.0', 'console_scripts', 'raises_exception')())
[raises_exception-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[raises_exception-1]   File "/workspaces/ros2/install/mre1636/lib/python3.12/site-packages/mre1636/raises_exception.py", line 4, in main
[raises_exception-1]     raise RuntimeError("Some exception!")
[raises_exception-1] RuntimeError: Some exception!
[ERROR] [raises_exception-1]: process has died [pid 255187, exit code 1, cmd '/workspaces/ros2/install/mre1636/lib/mre1636/raises_exception --ros-args -r __node:=raises_exception'].
```

The `launch.log` file
```bash
$ cat /home/ros/.ros/log/2024-12-20-19-11-59-571676-5200755c994a-255183/launch.log
1734721919.5729537 [INFO] [launch]: All log files can be found below /home/ros/.ros/log/2024-12-20-19-11-59-571676-5200755c994a-255183
1734721919.5731180 [INFO] [launch]: Default logging verbosity is set to INFO
1734721919.7796817 [INFO] [raises_exception-1]: process started with pid [255187]
1734721920.0653098 [raises_exception-1] Traceback (most recent call last):
1734721920.0655186 [raises_exception-1]   File "/workspaces/ros2/install/mre1636/lib/mre1636/raises_exception", line 33, in <module>
1734721920.0656092 [raises_exception-1]     sys.exit(load_entry_point('mre1636==0.1.0', 'console_scripts', 'raises_exception')())
1734721920.0656779 [raises_exception-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1734721920.0657406 [raises_exception-1]   File "/workspaces/ros2/install/mre1636/lib/python3.12/site-packages/mre1636/raises_exception.py", line 4, in main
1734721920.0659842 [raises_exception-1]     raise RuntimeError("Some exception!")
1734721920.0660613 [raises_exception-1] RuntimeError: Some exception!
1734721920.0806549 [ERROR] [raises_exception-1]: process has died [pid 255187, exit code 1, cmd '/workspaces/ros2/install/mre1636/lib/mre1636/raises_exception --ros-args -r __node:=raises_exception']
```
