### ISSUE TITLE
Random errors occurred when building ROS2 r2b3 with ament option "--parallel"

### ISSUE THREAD

**Issue by gaoethan** [ros2/ros2#415]
## Bug report

**Required Info:**

- Operating System: Ubuntu 16.04
  - 
- Installation type: source
  - 
- Version or commit hash: r2b3
  - 
- DDS implementation: default
  - 
- Client library (if applicable): N/A
  - 

#### Steps to reproduce issue

```
$ mkdir r2b3 && cd r2b3
$ wget https://raw.githubusercontent.com/ros2/ros2/release-latest/ros2.repos
$ vcs-import src < ros2.repos
$ src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install --parallel
```

#### Expected behavior
No build error
#### Actual behavior
Always different errors in each trial using `--parallel` but no error when building in serialization
#### Additional information

Here to give 2 errors as examples, as follows:

`example 1:`

```
Process package 'ament_pep257' with context:
--------------------------------------------------------------------------------
 source_space => /home/ethan/Myspace/rosdev/r2b3/src/ament/ament_lint/ament_pep257
-- [ament] Deploying: /home/ethan/Myspace/rosdev/r2b3/install/setup.sh
  build_space => /home/ethan/Myspace/rosdev/r2b3/build/ament_pep257
install_space => /home/ethan/Myspace/rosdev/r2b3/install
   make_flags => -j8, -l8
  build_tests => True
--------------------------------------------------------------------------------
+++ Building 'ament_pep257'
-- [ament] Deploying: /home/ethan/Myspace/rosdev/r2b3/install/setup.zsh

<== Command '. /home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck/ament_python__install.sh && /usr/bin/python3 setup.py develop --prefix /home/ethan/Myspace/rosdev/r2b3/install --no-deps' failed in '/home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck' with exit code '1'
SystemExit in ament_cppcheck: <== Command '. /home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck/ament_python__install.sh && /usr/bin/python3 setup.py develop --prefix /home/ethan/Myspace/rosdev/r2b3/install --no-deps' failed in '/home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck' with exit code '1'
-- [ament] Deploying: /home/ethan/Myspace/rosdev/r2b3/install/_order_packages.py
Traceback (most recent call last):
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 253, in run_command
    subprocess.check_call(cmd, shell=True, cwd=cwd, env=build_action.env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '. /home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck/ament_python__install.sh && /usr/bin/python3 setup.py develop --prefix /home/ethan/Myspace/rosdev/r2b3/install --no-deps' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build/cli.py", line 381, in process_in_parallel
    result = done_future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 280, in main
    return run(opts, context)
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 338, in run
    handle_build_action(on_install_ret, context)
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 270, in handle_build_action
    run_command(build_action, context)
  File "/home/ethan/Myspace/rosdev/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 262, in run_command
    sys.exit(msg)
SystemExit: <== Command '. /home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck/ament_python__install.sh && /usr/bin/python3 setup.py develop --prefix /home/ethan/Myspace/rosdev/r2b3/install --no-deps' failed in '/home/ethan/Myspace/rosdev/r2b3/build/ament_cppcheck' with exit code '1'
+++ Installing 'ament_pyflakes'
-- [ament] Deploying: /home/ethan/Myspace/rosdev/r2b3/install/share/ament_pyflakes/package.xml
-- [ament] Deploying: /home/ethan/Myspace/rosdev/r2b3/install/share/ament_pyflakes/environment/ament_prefix_path.sh
```

`example 2:`

```
Process package 'ament_cmake_core' with context:
--------------------------------------------------------------------------------
 source_space => /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core
  build_space => /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core
install_space => /home/ethan/Myspace/sandbox/r2b3/install
   make_flags => -j8, -l8
  build_tests => True
--------------------------------------------------------------------------------
+++ Building 'ament_cmake_core'
Running cmake because arguments have changed.
==> '. /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/cmake__build.sh && /usr/bin/cmake /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core -DBUILD_TESTING=1 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/ethan/Myspace/sandbox/r2b3/install' in '/home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core'
reading manifest file 'launch_testing.egg-info/SOURCES.txt'
writing manifest file 'launch_testing.egg-info/SOURCES.txt'
running build_ext
Creating /home/ethan/Myspace/sandbox/r2b3/install/lib/python3.5/site-packages/launch-testing.egg-link (link to .)
Adding launch-testing 0.0.0 to easy-install.pth file

Installed /home/ethan/Myspace/sandbox/r2b3/build/launch_testing
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Override CMake install command with custom implementation using symlinks instead of copying resources
[ 40%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_cyclic_closed.cpp.o
ImportError: 'from ament_package import parse_package_string' failed: No module named 'ament_package'
Make sure that you have installed 'ament_package', it is up to date and on the PYTHONPATH.
[ 17%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/rtps/writer/ReaderProxy.cpp.o
CMake Error at cmake/core/ament_package_xml.cmake:94 (message):
  execute_process(/usr/bin/python3
  /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core/cmake/core/package_xml_2_cmake.py
  /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core/package.xml
  /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/ament_cmake_core/package.cmake)
  returned error code 1
Call Stack (most recent call first):
  cmake/core/ament_package_xml.cmake:49 (_ament_package_xml)
  CMakeLists.txt:15 (ament_package_xml)


-- Configuring incomplete, errors occurred!
See also "/home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/CMakeFiles/CMakeOutput.log".
<== Command '. /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/cmake__build.sh && /usr/bin/cmake /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core -DBUILD_TESTING=1 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/ethan/Myspace/sandbox/r2b3/install' failed in '/home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core' with exit code '1'
SystemExit in ament_cmake_core: <== Command '. /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/cmake__build.sh && /usr/bin/cmake /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core -DBUILD_TESTING=1 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/ethan/Myspace/sandbox/r2b3/install' failed in '/home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core' with exit code '1'
Traceback (most recent call last):
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 253, in run_command
    subprocess.check_call(cmd, shell=True, cwd=cwd, env=build_action.env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '. /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/cmake__build.sh && /usr/bin/cmake /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core -DBUILD_TESTING=1 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/ethan/Myspace/sandbox/r2b3/install' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build/cli.py", line 381, in process_in_parallel
    result = done_future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 280, in main
    return run(opts, context)
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 331, in run
    handle_build_action(on_build_ret, context)
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 270, in handle_build_action
    run_command(build_action, context)
  File "/home/ethan/Myspace/sandbox/r2b3/src/ament/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 262, in run_command
    sys.exit(msg)
SystemExit: <== Command '. /home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core/cmake__build.sh && /usr/bin/cmake /home/ethan/Myspace/sandbox/r2b3/src/ament/ament_cmake/ament_cmake_core -DBUILD_TESTING=1 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/ethan/Myspace/sandbox/r2b3/install' failed in '/home/ethan/Myspace/sandbox/r2b3/build/ament_cmake_core' with exit code '1'
[ 42%] Building CXX object src/CMakeFiles/orocos-kdl.dir/frames_io.cpp.o
[ 44%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chain.cpp.o
```

**Comment by dirk-thomas** [comment]
Both cases look like a race condition where multiple packages try to write to the same install space. #167 has addressed similar issues since the latest release but I don't think it will covered your cases. I would recommend to build with the option `--isolated` to fallback to non-parallel builds for now.

We currently don't plan to develop `ament_tools` any further but at some point provide a more generic tool which can be used across ROS versions (see the [universal build tool](http://design.ros2.org/articles/build_tool.html) design article).
