### ISSUE TITLE
setuptools is outdated on Linux platform

### ISSUE THREAD

**Issue by minggangw** [ros2/ros2#512]
## Bug report

**Required Info:**

- Operating System:
Ubuntu 16.04
- Installation type:
Build from source
- Version or commit hash:
latest master
- DDS implementation:
Fast-RTPS
- Client library (if applicable):
  - 

#### Steps to reproduce issue
Follow the instruction (https://github.com/ros2/ros2/wiki/Linux-Development-Setup) to build ROS2 from scratch.
``` bash
minggang@minggang-Z97X:~/ros2_ws$colcon build --symlink-install
[0.361s] ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.package_identification.python': No module named 'setuptools.config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/lib/python3/dist-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/colcon_core/package_identification/python.py", line 10, in <module>
    from setuptools.config import read_configuration
ImportError: No module named 'setuptools.config'

```

#### Expected behavior
No error reported

#### Actual behavior
ImportError: No module named 'setuptools.config'

#### Additional information
The `setuptools` installed through `sudo apt install python3-colcon-common-extensions` is outdated(version 20.7.0-1). After upgrading by `sudo -H python3 -m pip install --upgrade setuptools`, which installs 39.2.0, the error went away.

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. Added to the instructions in https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/338dde366ebfa1e2603b08f317b06a953c986e6a...9ebb6c3dcea03ee741fb59262807922c1bfd6c79
